# Generated by Django 3.1.4 on 2020-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Enter the title of the alert', max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
